Repository hana-runner/hana-v-frontend, pull requests merged in 2024-06, with the labels that each got.

#51 feat: 카테고리 태그 컴포넌트 구현
  public/categoriesData.json
  public/interestsData.json
  public/transactionListData.json
  src/apis/apiClient.ts
  src/apis/interfaces/categoryApi.ts
  src/apis/interfaces/transactionApi.ts
  src/components/common/Tag.tsx
  src/components/transaction/TransactionList.tsx
  src/pages/Transaction.tsx
  src/types/category.d.ts
  src/types/transaction.d.ts
Labels: feat

#53 modify: components > index.ts 수정
  src/components/common/PeriodBtn.tsx
  src/components/index.ts
  src/components/transaction/HistoryOptionBoard.tsx
Labels: modify

#55 feat: Settings 페이지 추가
  src/App.tsx
  src/components/common/ToggleBtn.tsx
  src/components/index.ts
  src/pages/Settings.tsx
  src/pages/Transaction.tsx
  src/pages/index.ts
Labels: feat

#59 design: 달력 커스터마이징 & Transaction 페이지 디자인 수정
  src/components/transaction/AccountBoard.tsx
  src/components/transaction/HistoryOptionBoard.tsx
Labels: design

#64 feat: account id에 해당하는 계좌 정보 조회 기능 구현
  public/accountsData.json
  src/apis/apiClient.ts
  src/apis/interfaces/accountApi.ts
  src/components/transaction/AccountBoard.tsx
  src/types/account.d.ts
Labels: feat

#69 refactor: Base reseponse type 수정
  src/apis/apiClient.ts
Labels: refactor

#77 refactor: Base response type 수정
  src/types/response.d.ts
Labels: refactor

#81 ✨ 관심사 분석 거래 내역 - 연도 및 총 소비내역 구현
  src/App.tsx
  src/apis/apiClient.ts
  src/apis/imageApiClient.ts
  src/apis/interfaces/interestApi.ts
  src/components/common/MonthNavigationBtn.tsx
  src/components/transaction/HistoryOptionBoard.tsx
  src/pages/index.ts
  src/pages/interest/InterestAnalysis.tsx
  src/pages/interest/InterestDetail.tsx
  src/pages/interest/InterestTransaction.tsx
  src/types/interest.d.ts
  src/utils/CalculateDate.ts
Labels: feat

#83 feature 관심사 추가 페이지 - 화면 구현
  .eslintrc.cjs
  src/components/Navbar.tsx
  src/components/SelectBox.tsx
  src/components/common/Tooltip.tsx
  src/components/index.ts
  src/main.tsx
  src/pages/Home.tsx
  src/pages/interest/AddInterest.tsx
  src/pages/interest/Interests.tsx
  src/pages/interests/Interests.tsx
Labels: feat

#85 feat: 거래 내역 상세 페이지 구현
  src/App.tsx
  src/components/common/Tag.tsx
  src/components/index.ts
  src/components/transaction/AccountBoard.tsx
  src/components/transaction/ListCard.tsx
  src/components/transaction/TransactionList.tsx
  src/pages/TransactionDetail.tsx
  src/pages/index.ts
  src/types/account.d.ts
Labels: feat

#89 🐛 ApiClient에 token 추가
  src/apis/apiClient.ts
Labels: feat

#91 feat: 계좌 목록 조회 API 호출 기능
  src/apis/apiClient.ts
  src/apis/interfaces/accountApi.ts
  src/components/account/AccountCard.tsx
  src/components/account/MyAccount.tsx
  src/types/account.d.ts
Labels: feat

#104 rename: 알림 파일 이름 수정 및 폴더 경로 변경
  package.json
  src/App.tsx
  src/apis/apiClient.ts
  src/components/index.ts
  src/components/users/NotificationCard.tsx
  src/pages/alarm/Alarm.tsx
  src/pages/index.ts
  src/pages/notification/Notification.tsx
  src/pages/user/findPw/subPages/ResetPassword.tsx
  src/pages/user/login/Login.tsx
  src/utils/emailConverter.ts
  tailwind.config.js
Labels: modify

#116 refator: SelectBox 타입 수정
  src/components/SelectBox.tsx
  src/pages/AddAccount.tsx
Labels: refactor

#117 modify: 거래 내역 페이지 수정 및 리팩토링 & 충돌 해결
  src/App.tsx
  src/apis/apiClient.ts
  src/apis/interfaces/transactionApi.ts
  src/components/common/CancleBtn.tsx
  src/components/common/CategoryBtn.tsx
  src/components/common/MonthNavigationBtn.tsx
  src/components/index.ts
  src/components/transaction/HistoryOption.tsx
  src/components/transaction/HistoryOptionBoard.tsx
  src/components/transaction/ListCard.tsx
  src/components/transaction/TransactionList.tsx
  src/context/find-account-context/find-account-context.tsx
  src/pages/Transaction.tsx
  src/pages/TransactionDetail.tsx
  src/pages/index.ts
  src/pages/notification/Notification.tsx
  src/pages/transaction/ModifyCategory.tsx
  src/pages/transaction/Transaction.tsx
  src/pages/transaction/TransactionDetail.tsx
  src/pages/user/findPw/FindPw.tsx
  src/pages/user/findPw/subPages/VerifyId.tsx
  src/types/category.d.ts
  src/types/transaction.d.ts
Labels: conflict, modify, refactor

#123 modify: 거래내역 페이지 수정
  src/apis/apiClient.ts
  src/apis/interfaces/transactionApi.ts
  src/components/common/MonthNavigationBtn.tsx
  src/components/common/Tag.tsx
  src/components/transaction/AccountBoard.tsx
  src/components/transaction/HistoryOption.tsx
  src/components/transaction/HistoryOptionBoard.tsx
  src/components/transaction/TransactionList.tsx
  src/pages/transaction/Transaction.tsx
  src/types/transaction.d.ts
Labels: design, modify

#124 modify: 거래내역 상세 페이지 수정
  src/apis/apiClient.ts
  src/apis/interfaces/transactionHistoryApi.ts
  src/components/transaction/ListCard.tsx
  src/pages/transaction/Transaction.tsx
  src/pages/transaction/TransactionDetail.tsx
  src/types/transaction.d.ts
Labels: feat, modify

#126 feat: 카테고리 수정 기능 구현
  public/categoriesData.json
  src/apis/apiClient.ts
  src/apis/interfaces/categoryApi.ts
  src/apis/interfaces/transactionHistoryApi.ts
  src/components/transaction/ListCard.tsx
  src/pages/transaction/ModifyCategory.tsx
  src/pages/transaction/Transaction.tsx
  src/pages/transaction/TransactionDetail.tsx
Labels: feat

#127 design: 거래내역 수정 페이지 UI 구현
  src/App.tsx
  src/components/index.ts
  src/components/transaction/ListCard.tsx
  src/components/transaction/ModifyInterest.tsx
  src/pages/index.ts
  src/pages/transaction/ModifyTransactionDetail.tsx
Labels: design

#131 feat: 카테고리별 지출 합계 조회 기능 구현
  src/apis/apiClient.ts
  src/components/LegendElement.tsx
  src/components/consumption/MonthlyConsumption.tsx
  src/pages/Home.tsx
  src/types/account.d.ts
Labels: feat

#135 feat: 관심사 추가 페이지
  src/App.tsx
  src/apis/apiClient.ts
  src/apis/imageApiClient.ts
  src/apis/interfaces/interestApi.ts
  src/components/Loading.tsx
  src/components/SelectBox.tsx
  src/components/common/MenuSlide.tsx
  src/components/common/MonthNavigationBtn.tsx
  src/components/index.ts
  src/components/intereset/ImageCard.tsx
  src/components/intereset/ImageUploader.tsx
  src/components/intereset/InterestMenu.tsx
  src/components/intereset/InterestSubtitle.tsx
  src/context/interest/InterestContext.tsx
  src/context/register-context/register-context.tsx
  src/hooks/useInterestsQuery.ts
  src/main.tsx
  src/pages/interest/AddInterest.tsx
  src/pages/interest/Interests.tsx
  src/types/interest.d.ts
Labels: feat

#138 modify: context 폴더 이동
  src/components/context/find-account-context/find-account-context.tsx
  src/pages/interest/ModifyInterest.tsx
  src/pages/user/findId/FindId.tsx
  src/pages/user/findId/ShowId.tsx
  src/pages/user/findId/verification/VerifyCode.tsx
  src/pages/user/findId/verification/VerifyEmail.tsx
  src/pages/user/findPw/FindPw.tsx
  src/pages/user/findPw/subPages/ResetPassword.tsx
  src/pages/user/findPw/subPages/VerifyCode.tsx
  src/pages/user/findPw/subPages/VerifyEmail.tsx
  src/pages/user/findPw/subPages/VerifyId.tsx
  src/pages/user/login/Login.tsx
  src/pages/user/register/Regstier.tsx
  src/pages/user/register/subPages/RegisterEmail.tsx
  src/pages/user/register/subPages/RegisterId.tsx
  src/pages/user/register/subPages/RegisterName.tsx
  src/pages/user/register/subPages/RegisterSSN.tsx
  src/pages/user/register/subPages/VerifyCode.tsx
Labels: modify

#144 feat: 사용자 관심사 거래 상세 리스트 구현
  src/context/interest/InterestTransactionContext.tsx
  src/hooks/useInterestTransactionQuery.ts
  src/pages/interest/InterestAnalysis.tsx
  src/pages/interest/InterestTransaction.tsx
Labels: feat

#145 fix: 충돌 해결
  src/components/common/MonthNavigationBtn.tsx
  src/components/context/find-account-context/find-account-context.tsx
  src/utils/date.ts
Labels: conflict

#148 rename: 불필요한 파일 삭제
  src/utils/date.ts
Labels: modify

#149 refactor: 전역 모달 컴포넌트로 변경
  src/components/Modal.tsx
  src/components/intereset/ImageUploader.tsx
  src/context/ModalContext.tsx
  src/main.tsx
  src/pages/AddAccount.tsx
  src/pages/interest/AddInterest.tsx
  src/pages/interest/ModifyInterest.tsx
Labels: refactor

#150 style: 파일 이름 변경으로 인한 import 경로 수정
  src/components/common/MonthNavigationBtn.tsx
Labels: style

#152 fix: transaction 기능 복구
  src/App.tsx
  src/apis/apiClient.ts
  src/apis/interfaces/transactionApi.ts
  src/components/common/CancleBtn.tsx
  src/components/common/CategoryBtn.tsx
  src/components/common/Loading.tsx
  src/components/common/Tag.tsx
  src/components/index.ts
  src/components/transaction/AccountBoard.tsx
  src/components/transaction/HistoryOption.tsx
  src/components/transaction/HistoryOptionBoard.tsx
  src/components/transaction/ListCard.tsx
  src/components/transaction/ModifyInterest.tsx
  src/components/transaction/TransactionList.tsx
  src/pages/Transaction.tsx
  src/pages/index.ts
  src/pages/transaction/ModifyCategory.tsx
  src/pages/transaction/ModifyTransactionDetail.tsx
  src/pages/transaction/Transaction.tsx
  src/pages/transaction/TransactionDetail.tsx
  src/types/category.d.ts
  src/types/transaction.d.ts
Labels: fix

#163 feat: 카테고리별 소비 상세 기능
  src/apis/apiClient.ts
  src/apis/interfaces/accountApi.ts
  src/components/CategorySelect.tsx
  src/components/consumption/InterestConsumptionDetail.tsx
  src/components/index.ts
  src/pages/ConsumptionDetail.tsx
  src/pages/Home.tsx
  src/pages/account/AddAccount.tsx
  src/pages/consumption/ConsumptionDetail.tsx
  src/pages/index.ts
  src/types/account.d.ts
Labels: feat

#171 feat: 거래내역 수정 기능 구현
  package.json
  src/apis/apiClient.ts
  src/components/transaction/ListCard.tsx
  src/components/transaction/ModifyInterest.tsx
  src/components/transaction/TransactionList.tsx
  src/pages/transaction/ModifyTransactionDetail.tsx
  src/pages/transaction/Transaction.tsx
  src/types/transaction.d.ts
Labels: feat

#184 release: 배포 로직에 환경변수 추가
  .github/workflows/ci_and_cd.yml
Labels: release

#185 modify: modalContext에 onConfirm 추가
  src/context/ModalContext.tsx
Labels: modify

#186 fix: 카테고리별 소비 상세 페이지 뒤로가기 버튼 수정
  src/pages/consumption/ConsumptionDetail.tsx
Labels: fix

#189 refactor: 메뉴 페이지 로그아웃 로직 연결
  src/pages/Home.tsx
  src/pages/MenuTab.tsx
Labels: refactor

#190 fix: 모달 오류 수정
  src/components/Modal.tsx
  src/context/ModalContext.tsx
Labels: fix

#191 release: 배포 로직에 환경변수 추가
  .github/workflows/ci_and_cd.yml
Labels: release

#192 feat: home 화면의 account와 transaction 페이지 연결
  src/App.tsx
  src/components/account/AccountCard.tsx
  src/components/account/MyAccount.tsx
  src/components/transaction/AccountBoard.tsx
  src/pages/transaction/Transaction.tsx
Labels: feat

#199 modify: 불필요한 파일 제거
  public/accountsData.json
  public/interestsData.json
  public/transactionListData.json
  src/components/common/MenuSlide.tsx
Labels: modify

#200 feat: 관심사에 사용한 금액 프로세스 바, 6개월치 관심사 소비 금액 그래프 구현
  index.html
  src/App.tsx
  src/apis/apiClient.ts
  src/apis/interfaces/interestApi.ts
  src/components/index.ts
  src/components/intereset/CardRecommendation.tsx
  src/components/intereset/ImageCard.tsx
  src/components/intereset/ImageUploader.tsx
  src/components/intereset/InterestGraphFor6Months.tsx
  src/context/ModalContext.tsx
  src/context/interest/InterestContext.tsx
  src/context/interest/InterestTransactionContext.tsx
  src/hooks/useInterestTransactionQuery.ts
  src/hooks/useInterestsQuery.ts
  src/pages/Splash.tsx
  src/pages/interest/AddInterest.tsx
  src/pages/interest/InterestAnalysis.tsx
  src/pages/interest/InterestDetail.tsx
  src/pages/interest/InterestTransaction.tsx
  src/pages/interest/Interests.tsx
  src/pages/interest/ModifyInterest.tsx
  src/types/interest.d.ts
Labels: feat

#198 feat: 거래내역 수정 페이지 관심사 삭제 기능 추가
  src/App.tsx
  src/components/account/AccountInfo.tsx
  src/components/index.ts
  src/components/transaction/ModifyInterest.tsx
  src/components/transaction/TransactionList.tsx
  src/pages/TransactionDetail.tsx
  src/pages/account/AccountManagement.tsx
  src/pages/index.ts
  src/pages/transaction/ModifyCategory.tsx
  src/pages/transaction/ModifyTransactionDetail.tsx
  src/pages/transaction/TransactionDetail.tsx
  src/types/account.d.ts
  src/types/transaction.d.ts
Labels: feat

#202 fix: 거래내역 수정 기능 새로고침 오류 수정
  src/components/transaction/ListCard.tsx
  src/pages/transaction/ModifyTransactionDetail.tsx
Labels: fix

#204 fix: 계좌 등록 모달 수정
  src/pages/account/AddAccount.tsx
Labels: fix

#205 fix: transaction 관련 navigate path 수정
  src/App.tsx
  src/components/transaction/ListCard.tsx
  src/pages/transaction/ModifyCategory.tsx
  src/pages/transaction/ModifyTransactionDetail.tsx
Labels: fix

#206 feat: 비슷한 연령대와 관심사 소비 비교 구현
  src/App.css
  src/apis/apiClient.ts
  src/apis/interfaces/interestApi.ts
  src/components/index.ts
  src/components/intereset/InterestComparison.tsx
  src/pages/Home.tsx
  src/pages/interest/InterestAnalysis.tsx
  src/pages/interest/InterestDetail.tsx
  src/pages/interest/Interests.tsx
  src/types/interest.d.ts
Labels: feat

#207 feat: 카드 추천
  src/components/intereset/CardRecommendation.tsx
  src/main.tsx
  src/pages/interest/InterestAnalysis.tsx
  src/pages/interest/InterestTransaction.tsx
Labels: feat

#211 fix: 계좌관리 navigate 및 ui 수정
  src/components/Navbar.tsx
  src/components/account/AccountInfo.tsx
  src/components/common/NavIcon.tsx
  src/pages/MenuTab.tsx
  src/pages/Settings.tsx
  src/pages/account/AccountManagement.tsx
Labels: fix

#213 design: modify historyOption UI
  src/components/transaction/HistoryOptionBoard.tsx
Labels: design

#216 fix: 월별 소비 분석 범례 수정
  src/components/account/AccountCard.tsx
  src/components/consumption/MonthlyConsumption.tsx
  src/pages/Home.tsx
Labels: fix

#218 feat: 관심사 거래 내역 더보기 버튼
  src/pages/interest/InterestTransaction.tsx
Labels: feat

#220 fix: 같은 관심사 태그가 여러 개 보이는 오류 수정 및 UI 수정
  src/components/common/Tag.tsx
  src/components/transaction/ListCard.tsx
  src/components/transaction/TransactionList.tsx
  src/pages/transaction/ModifyTransactionDetail.tsx
Labels: design, fix

#225 fix: 전반적인 오류 수정
  public/img/shinhan_logo.png
  src/components/account/AccountCard.tsx
Labels: fix

#226 fix: 전반적인 오류 수정
  src/components/MenuCard.tsx
  src/components/UserWrapper.tsx
  src/components/account/AccountCard.tsx
  src/pages/Home.tsx
  src/pages/user/findId/FindId.tsx
  src/pages/user/findPw/FindPw.tsx
  src/pages/user/login/Login.tsx
  src/pages/user/register/Regstier.tsx
Labels: fix
