Repository hana-runner/hana-v-frontend, pull requests merged in 2024-05, with the labels that each got.

#2 :sparkles: Splash 화면 추가
  src/main.tsx
  src/pages/Splash.tsx
Labels: feat

#12 feat: axios 구현
  src/apis/apiClient.ts
  src/apis/interfaces/userApi.ts
  src/pages/FindId.tsx
  src/pages/FindIdEmail.tsx
  src/pages/FindPw.tsx
  src/pages/Login.tsx
Labels: feat

#15 fix: type을 interface로 변경
  src/App.tsx
  src/components/Modal.tsx
  src/components/Navbar.tsx
  src/types/interest.d.ts
  src/types/login.d.ts
  src/types/register.d.ts
  src/types/response.d.ts
  src/types/user.d.ts
Labels: fix

#17 feat: 아이디 찾기 verification 구현
  src/App.tsx
  src/pages/find-id/FindId.tsx
  src/pages/find-id/ShowId.tsx
  src/pages/find-id/VerifyCode.tsx
  src/pages/find-id/VerifyEmail.tsx
  src/pages/find-id/verification/ShowId.tsx
  src/pages/find-id/verification/VerifyCode.tsx
  src/pages/find-id/verification/VerifyEmail.tsx
  src/pages/find-pw/FindPw.tsx
Labels: feat

#19 design: 로그인 서비스 버튼 디자인 수정
  src/App.tsx
  src/pages/find-id/FindId.tsx
  src/pages/find-id/VerifyCode.tsx
  src/pages/find-id/VerifyEmail.tsx
  src/pages/find-id/verification/VerifyCode.tsx
  src/pages/login/Login.tsx
  src/pages/login/validation/id-validation.ts
  src/pages/login/validation/pw-validation.ts
Labels: design

#21 modify: 회원관련 디렉토리, 파일명 변경
  src/App.tsx
  src/pages/find-id/verification/ShowId.tsx
  src/pages/user/findId/FindId.tsx
  src/pages/user/findId/ShowId.tsx
  src/pages/user/findId/verification/VerifyCode.tsx
  src/pages/user/findId/verification/VerifyEmail.tsx
  src/pages/user/findPw/FindPw.tsx
  src/pages/user/index.ts
  src/pages/user/login/Login.tsx
  src/pages/user/login/validation/id-validation.ts
  src/pages/user/login/validation/pw-validation.ts
Labels: modify

#23 design: 아이디 찾기 프로세스 화면 정렬
  src/components/Navbar.tsx
  src/pages/user/findId/FindId.tsx
  src/pages/user/findId/ShowId.tsx
  src/pages/user/findId/Verified.tsx
  src/pages/user/findId/verification/VerifyCode.tsx
  src/pages/user/findId/verification/VerifyEmail.tsx
  src/pages/user/login/Login.tsx
Labels: design

#25 Design: 화면 레이아웃 버그 해결 및 스크롤 막기 구현
  src/App.css
  src/App.tsx
  src/components/types/login.d.ts
  src/components/types/register.d.ts
  src/components/types/response.d.ts
  src/components/types/user.d.ts
  src/index.css
  src/pages/index.ts
Labels: design

#28 feat: 회원가입 화면 구현
  src/App.tsx
  src/pages/user/login/Login.tsx
  src/pages/user/register/RegisterEmail.tsx
  src/pages/user/register/RegisterPw.tsx
Labels: feat

#33 modify: validation 함수 디렉토리 이동
  src/components/validation/id-validation.ts
  src/components/validation/pw-validation.ts
  src/pages/index.ts
  src/pages/user/index.ts
  src/pages/user/login/Login.tsx
  src/pages/user/register/RegisterEmail.tsx
  src/pages/user/register/RegisterId.tsx
  src/pages/user/register/RegisterName.tsx
  src/pages/user/register/RegisterPw.tsx
  src/pages/user/register/RegisterSSN.tsx
  src/pages/user/register/Regstier.tsx
  src/pages/user/register/register-context/context.tsx
  src/pages/user/register/register-context/provider.ts
  src/types/register.d.ts
Labels: modify

#36 feat: 거래내역 조회 기능 구현
  package.json
  public/img/logo3.png
  public/transactionListData.json
  src/App.tsx
  src/components/AccountBoard.tsx
  src/components/HistoryOption.tsx
  src/components/HistoryOptionBoard.tsx
  src/components/TransactionHistoryList.tsx
  src/components/common/PeoridBtn.tsx
  src/components/index.ts
  src/pages/TransactionHistories/TransactionHistory.tsx
  src/pages/index.ts
  src/types/accountBoardInfo.d.ts
  src/types/transactionHistory.d.ts
  src/utils/CalculateDate.ts
Labels: feat

#37 feat: 월별 소비 분석 조회 기능 구현
  package.json
  public/img/hana_logo.png
  src/App.css
  src/App.tsx
  src/components/CategorySelect.tsx
  src/components/LegendElement.tsx
  src/components/MenuCard.tsx
  src/components/Modal.tsx
  src/components/Navbar.tsx
  src/components/SelectBox.tsx
  src/components/account/AccountCard.tsx
  src/components/account/MyAccount.tsx
  src/components/consumption/MonthlyConsumption.tsx
  src/components/index.ts
  src/pages/AddAccount.tsx
  src/pages/ConsumptionDetail.tsx
  src/pages/Home.tsx
  src/pages/index.ts
Labels: design, feat

#40 fix: 사용자 관심사 목록 오류 수정
  src/App.css
  src/App.tsx
  src/apis/apiClient.ts
  src/apis/interfaces/interestApi.ts
  src/pages/Home.tsx
  src/pages/index.ts
  src/pages/interests/Interests.tsx
  src/pages/user/login/validation/id-validation.ts
  src/pages/user/login/validation/pw-validation.ts
  src/types/interest.d.ts
Labels: fix

#41 design: 입력값 에러 경고메세지 띄우기
  src/pages/user/findId/ShowId.tsx
  src/pages/user/login/Login.tsx
  src/pages/user/register/subPages/RegisterEmail.tsx
  src/pages/user/register/subPages/RegisterId.tsx
  src/pages/user/register/subPages/RegisterName.tsx
  src/pages/user/register/subPages/RegisterPw.tsx
  src/pages/user/register/subPages/RegisterSSN.tsx
  src/pages/user/register/subPages/VerifyCode.tsx
Labels: design, refactor

#45 modify: 전역 type 정리
  src/components/UserWrapper.tsx
  src/components/context/register-context/register-context.tsx
  src/pages/user/findId/FindId.tsx
  src/pages/user/findId/verification/VerifyCode.tsx
  src/pages/user/login/Login.tsx
  src/pages/user/register/Regstier.tsx
  src/pages/user/register/subPages/RegisterEmail.tsx
  src/pages/user/register/subPages/RegisterId.tsx
  src/pages/user/register/subPages/RegisterName.tsx
  src/pages/user/register/subPages/RegisterPw.tsx
  src/pages/user/register/subPages/RegisterSSN.tsx
  src/pages/user/register/subPages/VerifyCode.tsx
  src/types/actions.d.ts
  src/types/enums.ts
Labels: modify, refactor

#47 modify: components의 TransactionHistory 관련 내용 폴더화 & 파일명, Route 경로 수정
  src/App.tsx
  src/components/index.ts
  src/components/transaction/AccountBoard.tsx
  src/components/transaction/HistoryOption.tsx
  src/components/transaction/HistoryOptionBoard.tsx
  src/components/transaction/TransactionList.tsx
  src/pages/Transaction.tsx
  src/pages/TransactionHistories/TransactionHistory.tsx
  src/pages/index.ts
  src/types/transaction.d.ts
Labels: modify
